
'use client';

import * as React from 'react';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from '@/components/ui/scroll-area';

interface DisclaimerModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DisclaimerModal({ isOpen, onOpenChange }: DisclaimerModalProps) {
  return (
    <AlertDialog open={isOpen} onOpenChange={onOpenChange}>
      <AlertDialogContent className="max-w-2xl bg-slate-800 border-slate-700 text-gray-200">
        <AlertDialogHeader>
          <AlertDialogTitle className="font-headline text-2xl text-primary">QuantumGPT - Professional Disclaimer & Risk Statement</AlertDialogTitle>
          <AlertDialogDescription className="text-gray-400 text-sm pt-2">
            Please read the following information carefully before using QuantumGPT.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <ScrollArea className="max-h-[60vh] p-1 pr-4">
          <div className="space-y-4 text-gray-300 text-sm leading-relaxed">
            <p>
              QuantumGPT, powered by Blocksmith AI, was developed following extensive research in quantitative finance, market intelligence, and applied machine learning. Our models are built to deliver adaptive trading insights, deep behavioral analytics, and tailored strategies through real-time data analysis and visualization.
            </p>
            <p>
              While QuantumGPT provides cutting-edge analytical tools, it is not a financial advisor. All outputs, including strategy suggestions, market analyses, price predictions, and any other information generated by the system, are for educational and informational purposes only. They should not be construed as financial advice, investment recommendations, or solicitations to buy or sell any financial instruments.
            </p>
            <p>
              Trading and investing in cryptocurrencies and other financial assets carry significant risks, including the risk of substantial loss of principal. Market conditions can be highly volatile and unpredictable. Past performance is not indicative of future results. The AI-generated insights are based on historical data and statistical models, which may not accurately predict future market movements or account for all market dynamics and unforeseen events.
            </p>
            <p>
              Users of QuantumGPT are solely responsible for their own investment decisions and financial outcomes. Blocksmith AI and QuantumGPT do not guarantee the accuracy, completeness, or timeliness of the information provided. You should conduct your own thorough research and due diligence, and consult with a qualified financial advisor before making any investment decisions.
            </p>
            <p>
              Blocksmith AI, its affiliates, officers, directors, and employees assume no liability for any losses, damages, or outcomes, direct or indirect, arising from or related to the use of QuantumGPT or reliance on any information it provides. By using QuantumGPT, you acknowledge and agree to these terms and understand the inherent risks involved in financial markets.
            </p>
            <p className="font-semibold text-gray-100">
              Always trade responsibly and never invest more than you can afford to lose.
            </p>
          </div>
        </ScrollArea>
        <AlertDialogFooter className="pt-4">
          <AlertDialogAction
            onClick={() => onOpenChange(false)}
            className="bg-primary hover:bg-primary/80 text-primary-foreground"
          >
            Agree & Continue
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}

    